[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Thiết lập tốc độ Serial Monitor trùng với Serial.begin(115200)
monitor_speed = 115200

; (Tùy chọn) Bật tính năng hiển thị lỗi chi tiết nếu ESP32 bị crash
monitor_filters = esp32_exception_decoder

lib_deps =
    knolleary/PubSubClient @ ^2.8
